[book]
title = "Ordinal 序数理论"
language = "zh-cn"
src = "zh"


[output.html]
curly-quotes = true
git-repository-url = "https://github.com/decert-me/ordinals"

[output.html.print]
page-break = false

[preprocessor.katex]
after = ["links"]

